### PR TITLE
Fixed api.raw.history() and wrote associated tests.

### PR DESCRIPTION
**Pull request by Hiryus**

### CODE REVIEW

**Comment by ags131** [comment]
As an aside, private servers can have a different tick interval, 20 is just the default.

**Comment by ags131** [comment]
Another note, on servers not implementing history, it will return a 500 Error with `not implemented` as the body. May also want to account for the fact that history may not exist for that room on that tick.

**Comment by Hiryus** [comment]
Well, I will see once the endpoint will be correctly implemented on private servers: for now, they just don't use it at all :).
I have no idea what the response is when history does not exist. So I kept it simple for now.

**Comment by ags131** [comment]
Response if not implemented by a mod defaults to 500 error and `not
implemented`, with a mod it will entirely depend on what the mod returns.

**Pull request merged**
